### ISSUE TITLE
Generating fresh build getting errors 

### ISSUE THREAD

**Issue by mmiscool** [NaridaL/brep.ts#17]
Attempting to build using the following commands. 

```
npm install
npm run clean
npm run build 
```

Resulting error messages. 

```
@mmiscool ➜ /workspaces/brep.ts (master) $ npm run clean

> brepts@0.0.1 clean
> rm -r dist/* out/*

@mmiscool ➜ /workspaces/brep.ts (master ✗) $ npm run build

> brepts@0.0.1 build
> tsc & rollup -c & npm run minify

loaded rollup.config.js with warnings
(!) Unused external imports
default imported from external module 'rollup-plugin-sourcemaps' but never used

out/index.js → dist/bundle.js, dist/bundle.module.js...
[!] Error: Could not resolve entry (out/index.js)
Error: Could not resolve entry (out/index.js)
    at error (/workspaces/brep.ts/node_modules/rollup/dist/rollup.js:3460:30)
    at /workspaces/brep.ts/node_modules/rollup/dist/rollup.js:21474:17
    at async Promise.all (index 0)


> brepts@0.0.1 minify
> uglifyjs dist/bundle.js --output dist/bundle.min.js --compress --mangle && uglifyjs dist/bundle.module.js --output dist/bundle.module.min.js --compress --mangle

ERROR: ENOENT: no such file or directory, open 'dist/bundle.js'
    at Object.openSync (node:fs:585:3)
    at Object.readFileSync (node:fs:453:35)
    at read_file (/workspaces/brep.ts/node_modules/uglify-es/bin/uglifyjs:338:19)
    at /workspaces/brep.ts/node_modules/uglify-es/bin/uglifyjs:167:37
    at Array.forEach (<anonymous>)
    at Object.<anonymous> (/workspaces/brep.ts/node_modules/uglify-es/bin/uglifyjs:166:31)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1157:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
```

**Comment by NaridaL** [comment]
I tried this on two different machines and I get warnings but no errors.

For comparison, here are my node/npm versions. Which are you using?

```
aleonhard@x MINGW64 /c/ws/brep.ts (master)
$ node -v
v18.2.0

aleonhard@x MINGW64 /c/ws/brep.ts (master)
$ npm -v
8.15.1

```

**Comment by NaridaL** [comment]
Ah yeah, the fact that you're on ubuntu helped. There were some casing issues and the build script doesn't run on bash. It's a hack, but I added a `build-linux` script for now which should work. At least it did in my WSL instance.

**Comment by mmiscool** [comment]
Looks like the build is working now.
